version: "3.9"

services:
  postgres:
    container_name: "postgres"
    build:
      context: ./docker-images/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file: docker-images/postgres/.env.default
    volumes:
      - postgres:/var/lib/postgres/data

volumes:
  postgres:
    name: postgres-volume
